### ISSUE TITLE
README file里说change checkpoint directory，应该改成什么？

### ISSUE THREAD

**Issue by gigglegrig** [fendouai/Chinese-Text-Classification#3]
tf.flags.DEFINE_string("checkpoint_dir", "", "Checkpoint directory from training run")
是应该改第二项input么？改成什么

**Comment by fendouai** [comment]
你好，这个不需要更改，在文档的最后一步：

./eval.py --eval_train --checkpoint_dir="./runs/1459637919/checkpoints/"

"./runs/1459637919/checkpoints/"

这个是根据时间戳生成的，改成你的就可以了。

**Comment by gigglegrig** [comment]
@fendouai 你好，想问一下，我跑完以后生成了summary文件。如果想要生成plot来visualize 准确率（y轴）随着epoch#（X轴）的变化，是需要把summary文件load到tensorboard么？

**Comment by fendouai** [comment]
tensorbord 不是更方便吗

**Comment by gigglegrig** [comment]
@fendouai 谢谢回复。我这是第一次接触tensorflow，还停留在每个step记录accuracy然后手工plot出来的原始阶段。。。所以说run 完了以后用tensorboard去load生成的summary文件就能提取这些参数随着epoch的变化是么？

**Comment by fendouai** [comment]
是的，你了解一下 tensorbord 不用自己画。

**Comment by gigglegrig** [comment]
你好，我用原code跑了好几次，每个run都能生成一些summary文件，包括一个checkpoint folder和一个summaries folder。 Summaries folder有两个子文件夹分别是train和dev的summary信息。但是我用tensorboard去load这些文件的时候，load checkpoint文件可以生成每个tensor的300维向量表示。但是我想生成accuracy vs epoch，我去load train/dev summary file的时候却显示：No dashboards are active for the current data set.
下图为用tensorboard load checkpoint文件：
![image](https://user-images.githubusercontent.com/26666987/34075619-98c8177c-e299-11e7-995d-2b0b86cb6ee4.png)
![image](https://user-images.githubusercontent.com/26666987/34075600-7b4df3b0-e299-11e7-8c70-355e18f47741.png)

下图为用tensorboard load summary文件：
![image](https://user-images.githubusercontent.com/26666987/34075623-b01edd20-e299-11e7-843f-39e7334455d0.png)
![image](https://user-images.githubusercontent.com/26666987/34075624-b58eac86-e299-11e7-8dc5-6b1d041a319d.png)
希望你能帮我解答谢谢！
